# Generated by Django 5.1.7 on 2025-03-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0002_request_explanation_request_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
