# Generated by Django 5.1.6 on 2025-03-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0003_alter_request_first_name_alter_request_last_name'),
        ('delta', '0003_customuser_signature'),
    ]

    operations = [
    ]
