# Generated by Django 5.1.6 on 2025-03-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0004_merge_20250317_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='request',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='request',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(max_length=20),
        ),
    ]
