# Generated by Django 5.1.6 on 2025-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0006_request_explanation_request_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uh_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
